functional:
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Сайт должен быть доступен на различных устройствах
